---
abstract: 'DEPRECATED in favor of PerlGSL::DiffEq'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-GSLx-ODEIV2
provides:
  Math::GSLx::ODEIV2:
    file: lib/Math/GSLx/ODEIV2.pm
    version: 0.08
requires:
  PerlGSL::DiffEq: 0.08
  parent: 0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
